In [14]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix ,classification_report,precision_score, recall_score ,f1_score, roc_curve, roc_auc_score 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression 
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
#====================================================================
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split as tts
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [15]:
data = pd.read_csv(r"D:\Datasets\Drug Recomendation datas\drug_recommendation_dataset_binary.csv")
data.head()

Itching  Nodal_Skin_Eruptions  Shivering  Stomach_Pain  Vomiting  \
0        1                     0          1             1         1   
1        0                     0          0             1         1   
2        0                     0          0             1         0   
3        0                     0          1             0         1   
4        1                     0          1             1         1   

   Chest_Pain  Loss_of_Appetite  Yellow_Urine  Restlessness  Excessive_Hunger  \
0           0                 1             1             0                 0   
1           1                 0             0             1                 0   
2           1                 1             0             1                 1   
3           1                 0             1             1                 1   
4           1                 0             0             1                 0   

   ...  Yellowish_Skin  Abdominal_Pain  Weight_Loss  Irregular_Sugar_Level  \
0  ...               1               0            1                      0   
1  ...               0               0            1                      1   
2  ...               1               1            1                      0   
3  ...               0               0            1                      0   
4  ...               0               1            0                      0   

   Increased_Appetite  Headache  Muscle_Pain  Runny_Nose  Fast_Hart_Rate  \
0                   0         0            0           0               0   
1                   0         0            0           1               1   
2                   0         1            0           0               1   
3                   1         0            0           0               0   
4                   1         0            1           0               1   

   Drug_Recommendation  
0             Tramadol  
1            Metformin  
2         Azithromycin  
3          Chloroquine  
4           Cetirizine  

[5 rows x 30 columns]

In [16]:
data["Drug_Recommendation"].value_counts()

Drug_Recommendation
Azithromycin       114
Tramadol           109
Ursodiol           104
Chloroquine        103
Fluconazole        103
Pseudoephedrine    102
Omeprazole          97
Metformin           93
Cetirizine          91
Acyclovir           84
Name: count, dtype: int64

In [17]:
data["Drug_Recommendation"]=data["Drug_Recommendation"].replace(['Azithromycin','Tramadol','Ursodiol','Chloroquine','Fluconazole','Pseudoephedrine','Omeprazole','Metformin','Cetirizine','Acyclovir'],[1,2,3,4,5,6,7,8,9,10])

In [18]:
X = data.drop("Drug_Recommendation", axis = 1)
y = data["Drug_Recommendation"]

In [30]:
from sklearn.metrics import f1_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=135)

# Instantiate and train the Logistic Regression model
classimodel = LogisticRegression()  
classimodel.fit(X_train, y_train)

# Get the accuracy scores
trainscore = classimodel.score(X_train, y_train)
testscore = classimodel.score(X_test, y_test)

# Make predictions
y_pred = classimodel.predict(X_test)

# Calculate the F1 score
f1score = f1_score(y_test, y_pred, average='weighted')  # Choose appropriate average

# Print the F1 score and confusion matrix
print('F1 score:', f1score*10)
print('Confusion matrix:')
print(confusion_matrix(y_test, y_pred))


F1 score: 0.7761461586264996
Confusion matrix:
[[4 6 3 5 1 2 4 1 2 0]
 [4 4 3 2 2 0 4 4 1 1]
 [4 3 3 5 2 2 3 2 0 2]
 [3 7 4 2 3 3 2 1 0 1]
 [7 3 2 2 1 2 6 2 2 0]
 [1 3 5 3 1 0 4 0 3 3]
 [6 2 4 3 0 1 3 3 2 2]
 [1 3 1 1 3 3 8 2 0 2]
 [4 4 3 2 2 3 2 3 0 3]
 [0 1 3 3 2 0 4 4 0 2]]


In [31]:
from sklearn.ensemble import RandomForestClassifier

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=135)

# Instantiate and train the Random Forest model
rf_model = RandomForestClassifier(random_state=135)
rf_model.fit(X_train, y_train)

# Get the accuracy scores
train_score_rf = rf_model.score(X_train, y_train)
test_score_rf = rf_model.score(X_test, y_test)

# Make predictions
y_pred_rf = rf_model.predict(X_test)

# Calculate the F1 score
f1_score_rf = f1_score(y_test, y_pred_rf, average='weighted')  # Choose appropriate average

# Print the F1 score and confusion matrix
print('F1 score:', f1_score_rf * 10)
print('Confusion matrix:')
print(confusion_matrix(y_test, y_pred_rf))


F1 score: 0.9777819449266258
Confusion matrix:
[[3 2 0 7 3 3 2 5 0 3]
 [7 2 2 1 3 2 2 3 1 2]
 [4 1 2 6 3 1 3 4 0 2]
 [0 5 2 6 4 2 1 0 5 1]
 [2 5 6 4 2 3 3 0 2 0]
 [4 3 0 3 1 2 4 3 2 1]
 [6 4 2 3 1 2 4 2 0 2]
 [2 2 2 3 5 4 1 2 1 2]
 [8 2 3 1 2 4 2 1 2 1]
 [2 3 2 4 1 4 0 3 0 0]]


In [32]:
X_train

Itching  Nodal_Skin_Eruptions  Shivering  Stomach_Pain  Vomiting  \
117        0                     0          1             1         0   
646        0                     1          0             1         0   
888        0                     1          1             1         1   
183        1                     1          1             0         0   
225        0                     0          0             0         0   
926        0                     1          0             0         1   
443        1                     1          1             0         1   
589        0                     0          0             0         0   
212        1                     1          1             1         1   
32         0                     1          0             1         0   
934        0                     0          1             0         0   
153        0                     1          1             0         1   
721        0                     1          1             0         0   
914        1                     1          1             0         1   
387        1                     0          0             0         0   
202        0                     0          0             0         0   
493        1                     0          0             1         1   
49         1                     1          0             0         1   
196        1                     0          0             1         1   
845        0                     1          0             1         1   
82         0                     0          0             1         0   
867        0                     1          1             0         0   
169        0                     0          0             0         0   
94         1                     0          0             0         1   
674        1                     1          0             1         0   
108        0                     0          1             0         0   
4          1                     0          1             1         1   
954        0                     1          0             1         1   
451        1                     1          0             0         0   
741        1                     0          0             0         1   
113        0                     1          0             1         1   
655        0                     1          1             1         1   
89         0                     1          1             1         0   
829        1                     0          1             0         1   
949        1                     1          0             0         0   
158        1                     1          0             1         1   
230        0                     1          0             1         0   
675        0                     1          0             1         1   
636        1                     0          0             1         0   
734        1                     0          0             1         1   
781        1                     0          1             0         1   
814        0                     1          1             1         1   
755        0                     0          0             1         1   
146        1                     0          1             1         1   
445        1                     0          1             0         1   
181        0                     1          0             1         0   
775        0                     0          1             0         1   
944        1                     1          0             0         1   
20         1                     0          1             1         0   
842        1                     1          1             0         0   
294        0                     0          1             0         0   
620        0                     1          1             1         1   
728        1                     1          0             0         0   
709        1                     0          0             0    

In [33]:
y_train

117    10
646    10
888     8
183     4
225     5
926     3
443     3
589     2
212    10
32      2
934     9
153     3
721     3
914     3
387     8
202     4
493     2
49      8
196     3
845     2
82      3
867     8
169     1
94      3
674     4
108     1
4       9
954     7
451     6
741    10
113     8
655    10
89      9
829     1
949    10
158    10
230     1
675     7
636     3
734     2
781     8
814     5
755     3
146     7
445     8
181     1
775     6
944     7
20      9
842    10
294     9
620     5
728     5
709     8
43      7
258     7
939     1
850     3
580     5
811     5
512     8
236     7
836     7
130     7
419     4
409     8
536     2
833     4
971     9
392     2
228     7
354     1
59      9
144     2
660     8
676     3
152     6
498     9
299     5
496     9
73      2
864     6
979     1
797     8
609     9
899     9
424     1
457    10
987     9
35      6
135     1
724     6
249     4
44      9
807     7
757     2
749     9
421     1
692     3
995     3


In [21]:
import pandas as pd
from sklearn.metrics import f1_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split


# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=135)

# Instantiate and train the Decision Tree model
dt_model = DecisionTreeClassifier()  
dt_model.fit(X_train, y_train)

# Get the accuracy scores
train_score_dt = dt_model.score(X_train, y_train)
test_score_dt = dt_model.score(X_test, y_test)

# Make predictions
y_pred_dt = dt_model.predict(X_test)

# Calculate the F1 score
f1_score_dt = f1_score(y_test, y_pred_dt, average='weighted')

# Print the F1 score and confusion matrix
print('F1 score:', f1_score_dt)
print('Confusion matrix:')
print(confusion_matrix(y_test, y_pred_dt))

F1 score: 0.0846780445538161
Confusion matrix:
[[4 3 2 3 4 5 1 1 1 4]
 [2 5 1 2 4 0 2 4 1 4]
 [1 3 2 1 2 5 5 3 2 2]
 [1 2 6 1 3 4 2 3 2 2]
 [0 6 1 3 0 6 3 3 3 2]
 [3 2 6 3 2 1 2 3 1 0]
 [5 5 1 2 3 0 4 2 0 4]
 [0 4 4 1 1 3 4 2 0 5]
 [3 4 2 0 3 3 3 5 2 1]
 [0 1 3 3 4 2 2 1 3 0]]


In [22]:
import joblib

# Save the model to a file with a .pkl extension
joblib.dump(rf_model, 'DrugRec.pkl')

['DrugRec.pkl']

In [26]:
# Set display options to show all columns and more rows if needed
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Display the entire X_test DataFrame
print(X_test)


     Itching  Nodal_Skin_Eruptions  Shivering  Stomach_Pain  Vomiting  \
283        0                     1          0             1         0   
251        0                     1          1             1         0   
180        0                     1          1             1         1   
626        0                     0          1             1         1   
900        0                     1          0             0         1   
870        0                     1          1             1         0   
922        0                     1          1             1         1   
876        1                     0          0             1         0   
329        0                     1          0             1         0   
700        1                     0          0             1         0   
927        0                     0          0             1         1   
222        0                     0          0             1         1   
607        0                     0          1      

In [27]:


# Display the X_test DataFrame
X_test

Itching  Nodal_Skin_Eruptions  Shivering  Stomach_Pain  Vomiting  \
283        0                     1          0             1         0   
251        0                     1          1             1         0   
180        0                     1          1             1         1   
626        0                     0          1             1         1   
900        0                     1          0             0         1   
870        0                     1          1             1         0   
922        0                     1          1             1         1   
876        1                     0          0             1         0   
329        0                     1          0             1         0   
700        1                     0          0             1         0   
927        0                     0          0             1         1   
222        0                     0          0             1         1   
607        0                     0          1             1         0   
501        0                     1          0             0         0   
720        1                     1          1             1         0   
486        0                     1          0             0         1   
342        0                     0          1             0         1   
990        1                     1          0             0         1   
237        1                     0          1             1         0   
415        1                     1          1             0         0   
523        1                     1          1             1         0   
993        0                     0          0             1         1   
416        1                     0          1             1         0   
124        0                     1          0             1         0   
345        0                     0          0             1         0   
537        1                     0          0             0         1   
374        1                     1          0             1         1   
296        0                     0          1             0         1   
981        1                     1          0             0         1   
301        0                     0          0             0         1   
891        1                     0          1             1         1   
739        1                     0          1             1         0   
801        1                     0          0             1         1   
649        1                     1          1             0         1   
533        1                     1          0             1         1   
8          0                     0          1             0         1   
116        0                     1          1             0         0   
913        0                     1          1             0         1   
651        0                     1          1             1         0   
702        1                     1          1             1         1   
84         1                     1          1             0         0   
641        0                     0          1             1         1   
242        1                     1          0             1         1   
66         0                     0          0             1         0   
783        1                     0          0             1         0   
97         0                     1          1             1         1   
920        1                     0          0             0         1   
710        1                     0          0             0         1   
771        1                     1          1             1         0   
232        0                     0          1             1         1   
748        0                     1          0             1         1   
65         1                     1          1             1         1   
316        0                     1          0             1         0   
154        0                     1          0             1    

In [24]:
y_test

283     6
251     9
180    10
626     2
900     5
       ..
798     7
29      9
809     5
220     1
688     1
Name: Drug_Recommendation, Length: 250, dtype: int64

In [25]:
import pandas as pd
from sklearn.metrics import f1_score, confusion_matrix
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split


# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=135)

# Instantiate and train the SVM model
svm_model = SVC()  
svm_model.fit(X_train, y_train)

# Get the accuracy scores
train_score_svm = svm_model.score(X_train, y_train)
test_score_svm = svm_model.score(X_test, y_test)

# Make predictions
y_pred_svm = svm_model.predict(X_test)

# Calculate the F1 score
f1_score_svm = f1_score(y_test, y_pred_svm, average='weighted')

# Print the F1 score and confusion matrix
print('F1 score:', f1_score_svm)
print('Confusion matrix:')
print(confusion_matrix(y_test, y_pred_svm))


F1 score: 0.09855832919122455
Confusion matrix:
[[ 7  8  1  7  0  2  2  1  0  0]
 [ 5  6  3  3  2  0  2  3  1  0]
 [ 7  1  4  4  4  2  2  0  0  2]
 [ 5  9  4  3  2  2  1  0  0  0]
 [ 6  4  3  3  3  3  5  0  0  0]
 [ 3  4  4  5  3  0  3  0  0  1]
 [ 8  5  2  1  0  1  5  3  0  1]
 [ 2  4  4  2  3  3  4  1  0  1]
 [13  4  2  2  0  3  2  0  0  0]
 [ 0  3  5  3  3  0  2  3  0  0]]


In [ ]:
0	1	1	1	1	1	1	1	1	0	0	1	0	1	0	0	0	0	1	1	0	0	0	1	1	1	0	1	1

In [34]:
import joblib

# Load the model from the .pkl file
RFmodel = joblib.load('DrugRec.pkl')

# Define your input values
input_values = [[0,0,1,1,0,1,1,0,0,1,0,0,0,1,1,0,0,0,0,1,1,0,1,1,0,0,1,1,0
]]  # Replace Gender, Height, Weight with actual values

# Make predictions using the loaded model
predictions = RFmodel.predict(input_values)

# Print the predictions
print("Predicted BMI class:", predictions)


Predicted BMI class: [10]
